<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'csa_guzzle.client.addons_api' shared service.

$this->services['csa_guzzle.client.addons_api'] = $instance = new \GuzzleHttp\Client(array('base_url' => 'https://api-addons.prestashop.com', 'defaults' => array('timeout' => '5.0'), 'headers' => array('Accept' => 'application/json')));

(new \Csa\Bundle\GuzzleBundle\DependencyInjection\Configurator\ClientConfigurator(array(0 => ${($_ = isset($this->services['csa_guzzle.subscriber.cache']) ? $this->services['csa_guzzle.subscriber.cache'] : $this->load('getCsaGuzzle_Subscriber_CacheService.php')) && false ?: '_'}), NULL))->configure($instance);

return $instance;
