<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.admin.module.repository' shared service.

$this->services['prestashop.core.admin.module.repository'] = $instance = new \PrestaShop\PrestaShop\Core\Addon\Module\ModuleRepository(${($_ = isset($this->services['prestashop.core.admin.data_provider.module_interface']) ? $this->services['prestashop.core.admin.data_provider.module_interface'] : $this->load('getPrestashop_Core_Admin_DataProvider_ModuleInterfaceService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.data_provider.module']) ? $this->services['prestashop.adapter.data_provider.module'] : $this->getPrestashop_Adapter_DataProvider_ModuleService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.module.updater']) ? $this->services['prestashop.core.module.updater'] : $this->load('getPrestashop_Core_Module_UpdaterService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.logger']) ? $this->services['prestashop.adapter.legacy.logger'] : $this->services['prestashop.adapter.legacy.logger'] = new \PrestaShop\PrestaShop\Adapter\LegacyLogger()) && false ?: '_'}, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['prestashop.adapter.legacy.configuration']) ? $this->services['prestashop.adapter.legacy.configuration'] : $this->services['prestashop.adapter.legacy.configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration()) && false ?: '_'}->get("_PS_MODULE_DIR_"), ${($_ = isset($this->services['doctrine.cache.provider']) ? $this->services['doctrine.cache.provider'] : $this->services['doctrine.cache.provider'] = new \Doctrine\Common\Cache\FilesystemCache(($this->targetDirs[0].'/doctrine'))) && false ?: '_'});

$instance->setPrestaTrustChecker(${($_ = isset($this->services['prestashop.adapter.module.prestatrust.checker']) ? $this->services['prestashop.adapter.module.prestatrust.checker'] : $this->load('getPrestashop_Adapter_Module_Prestatrust_CheckerService.php')) && false ?: '_'});

return $instance;
