<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.admin.search_parameters' shared service.

return $this->services['prestashop.core.admin.search_parameters'] = new \PrestaShop\PrestaShop\Core\Search\SearchParameters();
