<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.core.module.updater' shared service.

return $this->services['prestashop.core.module.updater'] = new \PrestaShop\PrestaShop\Adapter\Module\ModuleDataUpdater(${($_ = isset($this->services['prestashop.core.admin.data_provider.addons_interface']) ? $this->services['prestashop.core.admin.data_provider.addons_interface'] : $this->load('getPrestashop_Core_Admin_DataProvider_AddonsInterfaceService.php')) && false ?: '_'}, ${($_ = isset($this->services['prestashop.core.admin.data_provider.module_interface']) ? $this->services['prestashop.core.admin.data_provider.module_interface'] : $this->load('getPrestashop_Core_Admin_DataProvider_ModuleInterfaceService.php')) && false ?: '_'});
